# Generated by Django 2.2.2 on 2019-07-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date_added',
        ),
        migrations.AddField(
            model_name='dish',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
