# Generated by Django 2.2.2 on 2019-09-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_ingredient_sauce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('cooking_time', models.IntegerField()),
                ('people', models.IntegerField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, 'More')], default=1)),
                ('cover_img', models.ImageField(default='media/smile.jpg', upload_to='')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('flavor', models.ManyToManyField(blank=True, default='', to='recipes.Flavor')),
                ('ingredient', models.ManyToManyField(help_text='such as; rice', related_name='recipe_ingredient', to='recipes.Ingredient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sauce', models.ManyToManyField(help_text='such as: slat', related_name='recipe_sauce', to='recipes.Ingredient')),
            ],
        ),
    ]
