# Generated by Django 2.2.2 on 2019-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(help_text='such as: rice', related_name='recipe_ingredient', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sauce',
            field=models.ManyToManyField(help_text='such as: salt', related_name='recipe_sauce', to='recipes.Sauce'),
        ),
    ]
