# Generated by Django 2.2.2 on 2019-09-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20190908_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='dish_pics')),
                ('rating', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'ordering': ['-date_added'],
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dish',
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='pic_path',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_category', to='recipe.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='flavor',
            field=models.ManyToManyField(blank=True, related_name='recipe_flavor', to='recipe.Flavor'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
