# Generated by Django 2.2.2 on 2019-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190926_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'ml')], default='g', max_length=2),
        ),
    ]
