# Generated by Django 2.2.2 on 2019-09-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190908_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_dish', to='recipes.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='flavor',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='pic_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
