# Generated by Django 2.2.2 on 2019-10-03 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_sauce_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
    ]
