# Generated by Django 2.2.2 on 2019-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20191003_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
