# Generated by Django 2.2.2 on 2019-10-11 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20191003_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flavor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'get_latest_by': ['date-added'], 'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='sauce',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'ml'), ('l', 'l'), ('kg', 'kg')], default='g', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=3, verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('ml', 'ml'), ('l', 'l'), ('kg', 'kg')], default='g', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'pic_path')},
        ),
    ]
