# Generated by Django 2.2.2 on 2019-10-11 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20191011_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='difficulty', verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=3, help_text='rating', verbose_name=django.core.validators.MaxValueValidator(limit_value=5)),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
